<?php

namespace Core\Traits;

trait CrudHooks
{
    /**
     * @return array
     * @author WeSSaM
     */
    public function creating(): array
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @return array
     * @author WeSSaM
     */
    public function updating($id): array
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     * @author WeSSaM
     */
    public function saving(): array
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * @param $model
     * @return mixed
     * @author WeSSaM
     */
    public function created($model): mixed
    {
        return $this->saved($model); // TODO: Change the autogenerated stub
    }

    /**
     * @param $model
     * @return mixed
     * @author WeSSaM
     */
    public function updated($model): mixed
    {
        return $this->saved($model); // TODO: Change the autogenerated stub
    }

    /**
     * @param $model
     * @return mixed
     * @author WeSSaM
     */
    public function saved($model): mixed
    {
        $this->syncRelations($model);
        return $model; // TODO: Change the autogenerated stub
    }
}
